 
version: "3"
services:

  app-1:
    image: asalem2020/app1
    ports:
     - "9999:8080"
    container_name: web-app1
  
  app-2:
    build: ./app2/Java-testapp/
    ports:
     - "7777:8080"
    container_name: web-app2

  nginx:
    build: ./nginx-container-reverse-proxy/
    ports:
     - "80:80"  
    container_name: reverse-proxy-project




